#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 25 19:47:31 2016

@author: Ramon
"""

import tushare as ts
import matplotlib.pyplot as plt
df=ts.get_hist_data('sz',start='2016-01-01')
df.to_excel('stock_sh.xlsx')
df.close.plot()
ax=plt.gca()
ax.invert_xaxis()
plt.show()

